# Generated by Django 3.2.5 on 2021-07-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the product', max_length=100)),
                ('price', models.IntegerField(help_text='Price of the product')),
                ('brand', models.CharField(help_text='Manufacturer of the product', max_length=100)),
                ('category', models.CharField(help_text='Category of the product', max_length=100)),
                ('picture', models.CharField(help_text='URL to the product picture', max_length=100)),
            ],
        ),
    ]
