# Generated by Django 3.2.5 on 2021-07-19 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0003_orderhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_ordered',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_ordered',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='date_ordered',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='is_ordered',
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='date_ordered',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='is_ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='products',
            field=models.ManyToManyField(to='shop.orderProduct'),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='ref_code',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
