# Generated by Django 3.2.5 on 2021-07-19 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210719_1033'),
    ]

    operations = [
        migrations.DeleteModel(
            name='orderHistory',
        ),
    ]
