# Generated by Django 3.2.5 on 2021-07-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pricture',
            field=models.ImageField(default='/user_pictures/default_profile_picture.png', upload_to='user_pictures'),
        ),
    ]
