# Generated by Django 3.2.5 on 2021-07-22 12:43

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=django_resized.forms.ResizedImageField(crop=None, default='default_profile_picture.png', force_format=None, keep_meta=True, quality=0, size=[250, 250], upload_to='user_pictures/'),
        ),
    ]
