# Generated by Django 3.2.5 on 2021-07-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='price',
            field=models.IntegerField(default=2137),
            preserve_default=False,
        ),
    ]
