# Generated by Django 3.2.5 on 2021-08-17 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0016_auto_20210817_0859'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(help_text='Review of a product', max_length=300)),
                ('rating', models.IntegerField(help_text='Rating of product')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(help_text='Reviewed product', on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
    ]
