# Generated by Django 3.2.5 on 2021-08-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_review_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
